version: '3'
services:
  nginx:
    image: nginx:alpine
    container_name: webserver
    volumes:
      - "./etc/nginx:/etc/nginx/conf.d"
      - "./etc/ssl:/etc/ssl"
      - "./web:/application"
    ports:
      - "${NGINX_PORT}:80"
      - "${NGINX_SSL_PORT}:443"
    command: /bin/sh -c "nginx -g 'daemon off;'"
    restart: ${NGINX_RESTART}
    depends_on:
      - php
      - php5

  php:
    build: ./containers/php
    container_name: php7
    working_dir: /application
    restart: ${PHP_RESTART}
    volumes:
      - ./web:/application
      - ./etc/php/php.ini:/etc/php5/fpm/conf.d/99-overrides.ini

  php5:
    build: ./containers/php5
    container_name: php5
    working_dir: /application
    restart: ${PHP5_RESTART}
    volumes:
      - ./web:/application
      - ./etc/php/php5.ini:/etc/php5/fpm/conf.d/99-overrides.ini

  mysqldb:
    image: mysql:5.7
    container_name: db
    restart: ${MYSQL_RESTART}
    env_file:
        - ".env"
    environment:
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
        - "${MYSQL_PORT}:3306"
    volumes:
        - ./data/db/mysql:/var/lib/mysql
        - ./etc/my.cnf:/etc/mysql/my.cnf

  mail:
    image: mail
    container_name: smtp
    restart: ${MAIL_RESTART}
    volumes:
      - ./data/mail:/output
    ports:
      - "${MAIL_PORT}:25"